title: ClearTK
baseurl: /cleartk
menu_names:
  - Home
  - Documentation
  - Tutorials
  - About
highlighter: pygments
markdown: kramdown
kramdown:
  parse_block_html: true
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
